/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Adminde.java
 *
 * Created on Dec 27, 2022, 9:44:02 AM
 */
package dbms;

import java.awt.event.ActionEvent;
import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class Adminde extends javax.swing.JFrame {
    private Object iconifyButton;
    private Object maximizeButton;
    
    public void actionPerformed(ActionEvent ae){
        if (ae.getSource().equals(iconifyButton)){
            setState(JFrame.ICONIFIED);
        }else if(ae.getSource().equals(maximizeButton)){
            setExtendedState(JFrame.MAXIMIZED_BOTH);
       }}

    /** Creates new form Adminde */
    public Adminde() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN DETAILS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 20, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Emp ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 60, 70, 17);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 60, 130, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 90, 60, 17);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(210, 90, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email ID :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 120, 70, 17);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 120, 130, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SID :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 150, 50, 17);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(210, 150, 130, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SName :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 180, 70, 17);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(210, 180, 130, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Server fail date and time :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 210, 190, 17);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(210, 210, 130, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 240, 70, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", " Inactive" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 240, 70, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reason :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 270, 70, 17);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(210, 270, 130, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter Emp ID : ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(450, 60, 120, 20);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(570, 60, 130, 22);

        jButton1.setText("Search");
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 100, 90, 22);

        jButton2.setText("View");
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 100, 90, 22);

        jButton3.setText("Notify");
        jPanel1.add(jButton3);
        jButton3.setBounds(180, 400, 100, 22);

        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Adminde().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
