/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * org.java
 *
 * Created on Dec 23, 2022, 2:56:05 PM
 */
package dbms;

import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class org extends javax.swing.JFrame {

    /** Creates new form org */
    public org() {
        initComponents();
        
    }
    orgde Organization = new orgde();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ORGANIZATION = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SMS BASED REMOTE SERVER MONITORING SYSTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 20, 650, 90);

        ORGANIZATION.setBackground(new java.awt.Color(255, 255, 255));
        ORGANIZATION.setFont(new java.awt.Font("Tahoma", 1, 18));
        ORGANIZATION.setForeground(new java.awt.Color(102, 0, 0));
        ORGANIZATION.setText("Organization");
        ORGANIZATION.setAlignmentY(1.2F);
        ORGANIZATION.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ORGANIZATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORGANIZATIONActionPerformed(evt);
            }
        });
        jPanel1.add(ORGANIZATION);
        ORGANIZATION.setBounds(230, 220, 290, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\wallpaper\\BLUE1.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ORGANIZATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORGANIZATIONActionPerformed
        Organization.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ORGANIZATIONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new org().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ORGANIZATION;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
